### ISSUE TITLE
Bug - if update is active in all branches it can no longer be managed via margarita

### ISSUE THREAD

**Issue by jelockwood** [jessepeterson/margarita#23]
While it may not be a configuration that most people might need I have found what I believe to be a bug. If you create two (or more) branches and have the updates enabled in both (i.e. all) branches, then the updates are no longer shown in the Margarita web interface. A scenario might be wanting to created a released branch with most updates enabled, and a test branch with all updates enabled. It would be quicker to create initially the released branch with all updates enabled and then disable those not wanted rather than enabling them all individually.

A workaround for when you get in to this state would either be to use the reposado command line or in margarita add an additional branch with no updates enabled, it will then show the other branches contents again.

I am running margarita under OS X 10.8.3 with flask. Updates have been downloaded to the local reposado repository.

**Comment by jessepeterson** [comment]
Commit 39d50b771dfd6f0cf4251bd621c07a68c7f31478 adds this very table footer, FYI.
