### ISSUE TITLE
StandardErrorPath and StandardOutPath

### ISSUE THREAD

**Issue by cgerke** [jessepeterson/margarita#28]
I wanted to change these paths so the log files reside inside the Margarita root which is a partition /Volumes/Data/www/margarita running on Yosemite.

I've noticed after a reboot the LaunchDaemon is creating the folder  /Volumes/Data/www/margarita causing my volume to mount to /Volumes/Data 1/www/margarita

I am guessing the daemon is running before the mount point is ready. Anyone else seen this behaviour?

**Comment by jessepeterson** [comment]
Is this an OS X client or server install? I believe OS X client won't (or at least used to not) mount volumes until a user logged in (and likewise unmounted volumes upon user logout). Mac OS X Server on the other hand would mount volumes upon boot. However launchd daemons start immediately regardless of external volumes.

**Comment by cgerke** [comment]
Client.

Going to try:

*sudo defaults write /Library/Preferences/SystemConfiguration/autodiskmount
AutomountDisksWithoutUserLogin -bool true*

or just leave the logs where they are.

**Comment by jessepeterson** [comment]
Sounds good. I'm interested in how the autodiskmount pref goes for you.

**Comment by cgerke** [comment]
Need to test this some more, its actually the internal disk that has been partitioned to:
/System
/Data

So I don't think autodiskmount is relevant here, I opened  ssh session to the system and /Data is already getting mounted prior to the loginwindow, it just seems that your daemon is creating /Volumes/Data before the partition gets mounted there. 

Going to test StartInterval or maybe WatchPath to see if it can delay the daemon.

**Comment by cgerke** [comment]
Only way I can get it working is to remove the StandardOutPath and StandardErrorPath, add a KeepAlive Pathstate to check for the volume, pipe the margarita.py to the log file. But now that I think about it, it was kinda dumb for me to want to store the log file in the www root anyway. I will leave it in /var/log

**Comment by jessepeterson** [comment]
Okay. Either way it seems it's more related to OS X and the nature launchd execution order than anything Margarita is doing. In other words any other software would also have this same issue. I'll close this issue. Thanks!
