### ISSUE TITLE
Displaying size of an update

### ISSUE THREAD

**Issue by gabesterr** [jessepeterson/margarita#29]
I have an environment where I need to build a couple reposadories that are size limited; is there a way to get the size of a given update displayed, and ideally sorted, in the margarita UI? I'd envision it being a separate column like version and release date.

**Comment by jessepeterson** [comment]
Just recently implemented sortable columns and download links, so it's certainly possible to have a size column without any trouble. However I think the UI is already a little crowded with columns along if you have very many branches.

But on the topic of repositories: how would you plan on making a size limited one? If you remove a non-deprecated update from an active catalog it'll just download again next `repo_sync` run, no?

**Comment by gabesterr** [comment]
Sorry, I should have clarified. I have a couple of reposado distribution points that only have so much storage capacity, so I must be careful which updates I add to them (i.e. 3.5MB app update, OK... 2.3GB content update for app, SKIP.) To that end being able to view the size of each update inline somewhere would be highly beneficial to me, but I realize it's an edge case.

**Comment by jessepeterson** [comment]
Well, you can now click on each link and see the size of each individual package for an update. It'd need to be a compelling case to further cramp the table with another column, though. Perhaps an option sometime.

**Comment by jessepeterson** [comment]
I'm going to close this issue and consider it resolved per the last comment. Thanks!
