### ISSUE TITLE
Any Chance of Adding OS Labels and Pakage download link from other Forks 

### ISSUE THREAD

**Issue by Lotusshaney** [jessepeterson/margarita#30]
These two functions have been a fantastic add on. Any chance of adding them into the main branch ?

https://github.com/loceee/margarita/commit/baba4d5bb5a1040f55e5fd63b79c7424f8ef8f2b
and
https://github.com/loceee/margarita/commit/00c47e5cfff72af2832faf0914e247b2fce512d5

**Comment by jessepeterson** [comment]
Stay tuned. :)

**Comment by jessepeterson** [comment]
Implementations of OS labels and download links are now rolled into Margarita with latest commits. Due to recent BackGrid changes I had to re-implemented a little rather than just merging the existing code. Thanks to @chymb for the ideas and code and @loceee for popularizing! :)

**Comment by Lotusshaney** [comment]
You are my hero, thanks

**Comment by loceee** [comment]
Agreed. My hero too :) margarita is the dog's bollocks!
