### ISSUE TITLE
support for --remove-config-data option?

### ISSUE THREAD

**Issue by arubdesu** [jessepeterson/margarita#32]
I would expect the GUI for this would require some figuring out, but as per https://managingosx.wordpress.com/2015/01/30/gatekeeper-configuration-data-and-xprotectplistconfigdata-and-munki-and-reposado-oh-my/ it would be nice to support this. (Although #4 purging is probably the more in-demand feature...)

**Comment by jessepeterson** [comment]
Feature is definitely planned. I'm waffling between implementing on the main page UI or on an update's individual page, probably default to the latter for now.

**Comment by arubdesu** [comment]
Yeah, wasn't sure this should actually be sent as a PR to reposado core as a post-repo_sync task, to just have it be on every run. I'll see if I can work on that, I did a good amount of digging/reading reposado. (Wanted to get this out there for other folks thinking similar things)

**Comment by gmarnin** [comment]
+1 for this feature

**Comment by andrewseago** [comment]
+1 for me as well

**Comment by jessepeterson** [comment]
wdas/reposado#36 PR was submitted to help support this feature

**Comment by jessepeterson** [comment]
Added some initial support for this in a4e745b411d69132c9855d10355c7e0910213396. Must have most recent version of reposado as well (wdas/reposado@7da4695c1e0cb2120f9aa5f1b5c2d3d4ff2971c6 or later). Let me know what you think!

**Comment by clburlison** [comment]
@jessepeterson Just pulled both the latest reposado & margarita. This feature is working for me. Much easier than my previous solution. 

Thanks!

**Comment by jessepeterson** [comment]
Thanks, folks. It's hasn't blown up for anybody yet so gonna close this up. Feel free to comment for any issues!
