### ISSUE TITLE
Apply queued changes (repo_sync necessary?)

### ISSUE THREAD

**Issue by Peter-Erik** [jessepeterson/margarita#35]
If i add an update to an branch for example 10.10.5 and click "Apple queued changes" I had to do an repo_sync to see the changes add the client side. On the browser i take a long time to see the changes if i do an refresh of the webpage then its quicker

**Comment by clburlison** [comment]
Peter-Erik, I believe this is an issue with my Nginx configuration not with margarita. Seeing as how you used my setup guide I'll try this weekend to see if I can't fix this. 

-Clayton

**Comment by Peter-Erik** [comment]
Thanks i was already doubted myself that i did something wrong, i did an git pull for Margarita and Repsado for update, thanks for your time Clayton!

**Comment by jessepeterson** [comment]
Sounds like you two have a lead on what's up. :) But the behavior should be as you expected: once you 'Apply queued changes' and wait 5-10 seconds for the catalogs to rebuild any changes should be made and visible to clients. Thanks for hopping in @clburlison!
