### ISSUE TITLE
Enhancement: GUI display signaling updates with config-data

### ISSUE THREAD

**Issue by poundbangbash** [jessepeterson/margarita#39]
The feature to remove config data is great but it requires knowing which updates have config data.  Some are obvious, like XProtect and Gatekeeper, but some sneak up, like the recent MRT configuration update.  I envision it like the D = deprecated badge where C = config data.  The badge would then be removed if the config data is removed from the update.

**Comment by jessepeterson** [comment]
Added a badge with 9a443ee38d028cd136f5de704ef2e293ad72779d.

**Comment by poundbangbash** [comment]
This ER has been incorporated
