### ISSUE TITLE
I can see gui of margarita but can't create new branch after updating margarita.

### ISSUE THREAD

**Issue by sprintership** [jessepeterson/margarita#47]

**Comment by sprintership** [comment]
I can see only blue stripe

**Comment by cashxx** [comment]
Just updated as well and having the same problem.  Have a text field to create branch name and then a blue "Create New Branch" button and that is it.  Just rebooted server and still nothing.  Ugg..

**Comment by jessepeterson** [comment]
@sprintership: are you still seeing issues? if you grab a fresh copy, restart your server, and perform a sync of margarita do things start working like for @cashxx?

**Comment by sprintership** [comment]
Hi, looks like ./repo_sync does the trick with branches after rebooting the server. IS there any fix to that ? Thx

**Comment by jessepeterson** [comment]
I'm unable to reproduce this issue. Can you provide a set of steps to reproduce including instructions on how you've setup your environment??

**Comment by franton** [comment]
Seen this before. It's usually file system ownership and permission issues.

**Comment by jessepeterson** [comment]
Closing issue as there was no follow-up from OP.
