### ISSUE TITLE
Missing 10.12 OS badges

### ISSUE THREAD

**Issue by poundbangbash** [jessepeterson/margarita#48]
I realize this is way early in the game but just adding it to the list for eventual addressing.

Updates that are included in the 10.12 .sucatalog are not showing the proper OS badge when listed in Margarita.

The latest XProtect update on June 20th shows it is part of the 10.12 catalog per repoutil --info

```
bash-3.2# repoutil --info 031-64856
Product:       031-64856
Title:         XProtectPlistConfigData
Version:       1.0
Size:          23.3 KB
Post Date:     2016-06-20 23:42:44
RestartNeeded: No
Status:        Downloaded
Location:      /Volumes/ExtHD/reposado/html/content/downloads/03/32/031-64856
AppleCatalogs:
               http://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
               http://swscan.apple.com/content/catalogs/others/index-10.11customerseed-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
               https://swscan.apple.com/content/catalogs/others/index-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Branches:
               home
HTML Description:
```

But Margarita doesn't show that on the webpage.

![screenshot 2016-06-21 11 10 15](https://cloud.githubusercontent.com/assets/1416288/16237159/c683fa28-37a0-11e6-9484-90b64fbc9f6d.png)

**Comment by poundbangbash** [comment]
Poking around it looks like it's just a matter of adding a new catalog value.  Making that change worked on my test system.

PR at https://github.com/jessepeterson/margarita/pull/49/commits/07a3bd5cf66f95c5ccf1611982126738f060a6e1

**Comment by jessepeterson** [comment]
Thanks for the PR! Merged!
