### ISSUE TITLE
Margarita start failed! ImportError: no module named reposadolib 

### ISSUE THREAD

**Issue by DeutscheBahnMuK** [jessepeterson/margarita#51]
Dear Jesse,

Symbolic Links are set up, as you see in this Screenshot:

![bildschirmfoto 2017-05-12 um 11 17 10](https://cloud.githubusercontent.com/assets/28646888/25991728/98e022cc-3704-11e7-87fc-a28161ea119d.png)

This is the Error Message when i try to start margarita:

c:\Program Files>python "c:\Program Files\margarita-master\margarita.py" -p -8089 -b 127.0.0.1 -d
Traceback (most recent call last):
  File "c:\Program Files\margarita-master\margarita.py", line 17, in <module>
    from reposadolib import reposadocommon
ImportError: No module named reposadolib

Any Idea how to solve this problem?

Best regards

Thomas =)

**Comment by DeutscheBahnMuK** [comment]
The Symbolic Link in windows must be set with option
/D /J

Than it works!

**Comment by jessepeterson** [comment]
Good to know! I don't have experience with this on windows so thanks for noting!
