### ISSUE TITLE
Web UI no longer letting me create, remove, or modify branches

### ISSUE THREAD

**Issue by stsmith07** [jessepeterson/margarita#54]
the list of software updates appears fine and it shows all of my branches and whats applied, but if I try to apply any queued changes, create new branches, or remove them, it will typically remove all branches.

Any idea on how to fix this? Any logs or data I can provide?

**Comment by e-manjr** [comment]
I had similar issue, it turns out the disk that the CatalogBranches.plist resides on was full and no data couldn't be written. After enlarging it I was able to use the web to create branches without it deleting existing ones. I hope this helps

**Comment by jessepeterson** [comment]
Closing this ancient issue. Please file another one if it persists. Also - getting the Python output as a log would be most helpful. Thanks!
