### ISSUE TITLE
Feature suggestion: sortable columns

### ISSUE THREAD

**Issue by gregneagle** [jessepeterson/margarita#6]
It would nice to be able to sort updates by clicking on a column header.

**Comment by jessepeterson** [comment]
Only three years late, but I just merged a branch integrating Backgrid — a column-sorting paged table layout JS framework. Thanks for the suggestion!

**Comment by jessepeterson** [comment]
One question is the size of the paged results. Current hard-coded at 20 I wondering if this should be lessened and/or made adjustable.

**Comment by tallfunnyjew** [comment]
hey-OOOOOO! thanks, jesse!
